config/routes.rb
Rails.application.routes.draw do

  #Static Pages
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/help', to: 'static_pages#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'products/new'
  get '/products/:id', to: 'products#show'
  get '/products', to: 'products#index'


  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'



  #RESTFUL routes
  resources :products, :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :reviews
end

app/models/review.rb
class Reviews < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :reviews  

    before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(permitted_product_params)
      if @product.save
        flash[:success] = 'Product was successfully created.'
        format.html { redirect_to @product }
      else
        format.html {render :new}
      end

  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  def update #responds to patch request
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(permitted_product_params)
        flash[:success] = 'Product was successfully updated.'
        format.html { redirect_to product_url }
      else
        render 'edit'
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

private

  def permitted_product_params
    params.require(:product).permit(:name, :price, :category, :product_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create # action - corresponds to POST
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
      #do something
    else
      #error message
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create #responds to post request
    @user = User.new(permitted_user_params)
    respond_to do |format|
      if @user.save
        log_in(@user)
        flash[:success]= 'User was successfully created.'
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @user = User.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destoyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update #responds to patch request
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(permitted_user_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to user_url }
      else
        render 'edit'
      end
    end
  end



  private

    def permitted_user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redmartrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <%= render 'partials/header' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<ul>
  <li><%= link_to "Home",   '/' %></li>
  <li><%= link_to "Help",   '/help' %></li>
  <li><%= link_to "About",   '/about' %></li>
  <li><%= link_to "Sign Up", '/signup' %></li>
  <% if logged_in? %>
    <li><%= link_to 'Users', '#' %></li>
    <li><%= link_to 'Profile', current_user %></li>
    <li><%= link_to 'Settings', '#' %></li>
    <li><%= link_to 'Log out', '/logout', method: 'delete' %></li>
  <% else %>
    <li><%= link_to "Log In", '/login' %></li>
  <% end %>
</ul>

app/views/products/edit.html.erb
<h1>Products#edit</h1>

  <div class="field">
  <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :category %>
    <%= f.text_field :category %>

    <%= f.label :product_id, "Product Id" %>
    <%= f.number_field :product_id %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.submit "Save changes"%>
  <% end %>
  </div>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Product Id</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td> <%= product.name %> </td>
      <td> <%= product.category %> </td>
      <td> <%= product.product_id %> </td>
      <td> <%= product.price %> </td>
      <td> <%= link_to 'Show', product %> </td>
      <td> <%= link_to 'Edit', edit_product_path(product) %> </td>
      <td> <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?'}%> </td>
    </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

<%= form_for(@product) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :product_id, "Product Id" %>
  <%= f.number_field :product_id %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.submit "Create New Product" %>
<% end %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Product Id:</strong>
  <%= @product.product_id %>
</p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>

  <div class="field">
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.text_field :password_confirmation %>

    <%= f.submit "Save changes"%>
  <% end %>
  </div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td> <%= user.name %> </td>
      <td> <%= user.email %> </td>
      <td> <%= link_to 'Show', user %> </td>
      <td> <%= link_to 'Edit', edit_user_path(user) %> </td>
      <td> <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?'}%> </td>
    </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password%>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Password Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>